### ISSUE TITLE
Erro ao executar o nuxtool no Linux Mint  17.2 Rafaela

### ISSUE THREAD

**Issue by fernandopetry** [gmasson/nuxtool#2]
Erro ao executar nuxtool, anexo imagem do erro.

Info do sistema:
Linux pc-fernando 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

![nuxtool](https://cloud.githubusercontent.com/assets/2379937/9028114/35f22850-3944-11e5-93dd-7d5bbb7caab1.png)

**Comment by gmasson** [comment]
poxa, que estranho cara, aqui ta funcionando normal.. também estou usando o Mint.. só que o Rebecca

![captura de tela - 02-08-2015](https://cloud.githubusercontent.com/assets/8229909/9028233/d8814fd0-3947-11e5-99ea-58c0f4721c9e.png)
